# Generated by Django 5.2.4 on 2025-08-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checker',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
