# Generated by Django 5.2.4 on 2025-08-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_checker_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
