# Generated by Django 5.2.4 on 2025-08-10 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alert_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checker',
            old_name='content_type',
            new_name='api',
        ),
        migrations.RemoveField(
            model_name='checker',
            name='object_id',
        ),
    ]
