# Generated by Django 5.2.4 on 2025-08-10 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_rename_content_type_checker_api_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='alerts', to=settings.AUTH_USER_MODEL),
        ),
    ]
