# Generated by Django 5.2.4 on 2025-08-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_alert_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_published',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
