# Generated by Django 5.2.4 on 2025-08-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_alert_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
