# Generated by Django 5.2.4 on 2025-08-25 08:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0008_alter_alert_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='check_interval',
            field=models.IntegerField(default=3600),
        ),
        migrations.AddField(
            model_name='alert',
            name='last_checked',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
