# Generated by Django 5.2.4 on 2025-08-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openweatherapi',
            name='timezone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
