# Generated by Django 5.2.4 on 2025-08-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_notifications_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='local_date',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='local_time',
            field=models.CharField(blank=True, null=True),
        ),
    ]
