# Generated by Django 5.2.4 on 2025-08-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_local_date_notification_local_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
